// Generated by scripts/import-card-art.mjs — do not edit by hand.
// Maps each card id to its art file (custom art if imported, else the SVG placeholder).
export const CARD_ART: Record<string, string> = {
  "ashcrag": "/cards/ashcrag.webp",
  "mistpool": "/cards/mistpool.webp",
  "emberWhelp": "/cards/emberWhelp.webp",
  "flameScout": "/cards/flameScout.webp",
  "cinderHound": "/cards/cinderHound.webp",
  "ridgeWyvern": "/cards/ridgeWyvern.webp",
  "magmaBrute": "/cards/magmaBrute.webp",
  "firebrandAdept": "/cards/firebrandAdept.webp",
  "sparkBolt": "/cards/sparkBolt.webp",
  "combust": "/cards/combust.webp",
  "recklessCharge": "/cards/recklessCharge.webp",
  "infernoWave": "/cards/infernoWave.webp",
  "tideSprite": "/cards/tideSprite.webp",
  "pearlDiver": "/cards/pearlDiver.webp",
  "mistSerpent": "/cards/mistSerpent.webp",
  "shoalGuardian": "/cards/shoalGuardian.webp",
  "tidalLeviathan": "/cards/tidalLeviathan.webp",
  "coralElder": "/cards/coralElder.webp",
  "insight": "/cards/insight.webp",
  "recallWave": "/cards/recallWave.webp",
  "healingTide": "/cards/healingTide.webp",
  "frostLock": "/cards/frostLock.webp",
  "growthSurge": "/cards/growthSurge.webp",
  "wanderingGolem": "/cards/wanderingGolem.webp",
  "scrapAutomaton": "/cards/scrapAutomaton.webp"
};
