import type { CardDefinition } from './types';

export const CARDS: Record<string, CardDefinition> = {
  ashcrag: {
    id: 'ashcrag',
    name: 'Ashcrag',
    type: 'land',
    text: 'Tap: Add one flame mana.',
    colors: [],
    producesColor: 'flame',
  },
  mistpool: {
    id: 'mistpool',
    name: 'Mistpool',
    type: 'land',
    text: 'Tap: Add one tide mana.',
    colors: [],
    producesColor: 'tide',
  },

  emberWhelp: {
    id: 'emberWhelp',
    name: 'Ember Whelp',
    type: 'creature',
    text: 'A small, restless flame given claws.',
    cost: { generic: 0, flame: 1 },
    colors: ['flame'],
    power: 1,
    toughness: 1,
  },
  flameScout: {
    id: 'flameScout',
    name: 'Flame Scout',
    type: 'creature',
    text: 'Runs ahead of the war-band, burning the way clear.',
    cost: { generic: 0, flame: 1 },
    colors: ['flame'],
    power: 2,
    toughness: 1,
  },
  cinderHound: {
    id: 'cinderHound',
    name: 'Cinder Hound',
    type: 'creature',
    text: 'Hunts by scent of smoke.',
    cost: { generic: 1, flame: 1 },
    colors: ['flame'],
    power: 2,
    toughness: 2,
  },
  ridgeWyvern: {
    id: 'ridgeWyvern',
    name: 'Ridge Wyvern',
    type: 'creature',
    text: 'Flying',
    cost: { generic: 2, flame: 1 },
    colors: ['flame'],
    power: 3,
    toughness: 2,
    keywords: ['flying'],
  },
  magmaBrute: {
    id: 'magmaBrute',
    name: 'Magma Brute',
    type: 'creature',
    text: 'Trample',
    cost: { generic: 3, flame: 1 },
    colors: ['flame'],
    power: 5,
    toughness: 4,
    keywords: ['trample'],
  },
  firebrandAdept: {
    id: 'firebrandAdept',
    name: 'Firebrand Adept',
    type: 'creature',
    text: 'When this enters, deal 1 damage to any target.',
    cost: { generic: 2, flame: 1 },
    colors: ['flame'],
    power: 2,
    toughness: 3,
    effectKey: 'firebrandAdeptEtb',
    targetKind: 'any',
  },
  sparkBolt: {
    id: 'sparkBolt',
    name: 'Spark Bolt',
    type: 'spell',
    text: 'Deal 3 damage to any target.',
    cost: { generic: 0, flame: 1 },
    colors: ['flame'],
    effectKey: 'dealDamage3',
    targetKind: 'any',
  },
  combust: {
    id: 'combust',
    name: 'Combust',
    type: 'spell',
    text: 'Deal 5 damage to target creature.',
    cost: { generic: 2, flame: 1 },
    colors: ['flame'],
    effectKey: 'dealDamage5Creature',
    targetKind: 'creature',
  },
  recklessCharge: {
    id: 'recklessCharge',
    name: 'Reckless Charge',
    type: 'spell',
    text: 'Target creature gets +3/+0 until end of turn.',
    cost: { generic: 1, flame: 1 },
    colors: ['flame'],
    effectKey: 'pumpPower3',
    targetKind: 'creature',
  },
  infernoWave: {
    id: 'infernoWave',
    name: 'Inferno Wave',
    type: 'spell',
    text: 'Deal 2 damage to all creatures.',
    cost: { generic: 4, flame: 1 },
    colors: ['flame'],
    effectKey: 'damageAllCreatures2',
    targetKind: 'none',
  },

  tideSprite: {
    id: 'tideSprite',
    name: 'Tide Sprite',
    type: 'creature',
    text: 'Flying',
    cost: { generic: 0, tide: 1 },
    colors: ['tide'],
    power: 1,
    toughness: 1,
    keywords: ['flying'],
  },
  pearlDiver: {
    id: 'pearlDiver',
    name: 'Pearl Diver',
    type: 'creature',
    text: 'Patient and hard to shift.',
    cost: { generic: 0, tide: 1 },
    colors: ['tide'],
    power: 1,
    toughness: 3,
  },
  mistSerpent: {
    id: 'mistSerpent',
    name: 'Mist Serpent',
    type: 'creature',
    text: 'Flying',
    cost: { generic: 2, tide: 1 },
    colors: ['tide'],
    power: 3,
    toughness: 4,
    keywords: ['flying'],
  },
  shoalGuardian: {
    id: 'shoalGuardian',
    name: 'Shoal Guardian',
    type: 'creature',
    text: 'Holds the line.',
    cost: { generic: 1, tide: 1 },
    colors: ['tide'],
    power: 1,
    toughness: 4,
  },
  tidalLeviathan: {
    id: 'tidalLeviathan',
    name: 'Tidal Leviathan',
    type: 'creature',
    text: 'A slow, inevitable tonnage of scale and muscle.',
    cost: { generic: 4, tide: 1 },
    colors: ['tide'],
    power: 6,
    toughness: 6,
  },
  coralElder: {
    id: 'coralElder',
    name: 'Coral Elder',
    type: 'creature',
    text: 'When this enters, draw a card.',
    cost: { generic: 3, tide: 1 },
    colors: ['tide'],
    power: 3,
    toughness: 5,
    effectKey: 'drawCardEtb',
    targetKind: 'none',
  },
  insight: {
    id: 'insight',
    name: 'Insight',
    type: 'spell',
    text: 'Draw 2 cards.',
    cost: { generic: 1, tide: 1 },
    colors: ['tide'],
    effectKey: 'drawCards2',
    targetKind: 'none',
  },
  recallWave: {
    id: 'recallWave',
    name: 'Recall Wave',
    type: 'spell',
    text: "Return target creature to its owner's hand.",
    cost: { generic: 1, tide: 1 },
    colors: ['tide'],
    effectKey: 'bounceCreature',
    targetKind: 'creature',
  },
  healingTide: {
    id: 'healingTide',
    name: 'Healing Tide',
    type: 'spell',
    text: 'You gain 5 life.',
    cost: { generic: 1, tide: 1 },
    colors: ['tide'],
    effectKey: 'gainLife5',
    targetKind: 'none',
  },
  frostLock: {
    id: 'frostLock',
    name: 'Frost Lock',
    type: 'spell',
    text: "Tap target creature. It doesn't untap during its controller's next untap step.",
    cost: { generic: 2, tide: 1 },
    colors: ['tide'],
    effectKey: 'tapAndFreeze',
    targetKind: 'creature',
  },
  growthSurge: {
    id: 'growthSurge',
    name: 'Growth Surge',
    type: 'spell',
    text: 'Target creature gets +0/+3 until end of turn.',
    cost: { generic: 0, tide: 1 },
    colors: ['tide'],
    effectKey: 'pumpToughness3',
    targetKind: 'creature',
  },

  wanderingGolem: {
    id: 'wanderingGolem',
    name: 'Wandering Golem',
    type: 'creature',
    text: 'Made of nothing but old road and older stone.',
    cost: { generic: 3 },
    colors: [],
    power: 3,
    toughness: 3,
  },
  scrapAutomaton: {
    id: 'scrapAutomaton',
    name: 'Scrap Automaton',
    type: 'creature',
    text: 'Assembled from whatever was lying around.',
    cost: { generic: 2 },
    colors: [],
    power: 2,
    toughness: 2,
  },
};

export function getCard(defId: string): CardDefinition {
  const def = CARDS[defId];
  if (!def) throw new Error(`Unknown card id: ${defId}`);
  return def;
}
